### ISSUE TITLE
Debug to file causes a Segmentation Fault

### ISSUE THREAD

**Issue by santanor** [KVault/NESulator#32]
Recently, any logging into a file causes the project to crash. 

Repro (On branch ppu):
-Run the DonkeyKong.nes ROM
-Set the file logging to `FileDebug`
-Run the project in debug mode
-It should fail on this line `vfprintf(file, log, args);` that lives under the `log_to_file` function

**Comment by the-c0d3r** [comment]
Might I suggest using something like [zlog](https://github.com/HardySimpson/zlog) library rather than rolling your own? That way you don't need to care about thread safety, as well as log rotations and log levels. And you don't need to pass around the reference as well. You can get it from global context.

**Comment by santanor** [comment]
Hey @the-c0d3r 
It's good to see you around again :)  
The reason why we didn't do it in the first place is that the logs evolved from plain `printf` to something a bit more complex and it kind of did it on its own hahaha. 

That library is definitely worth looking at, assuming it's multiplatform and that we can distribute it statically with the repo (we kind of want to do that...) 

I'm bringing @alexsaezm on the loop, he'll asses the situation and hook in the library if it suit us :) 

Thanks for the suggestion!

**Comment by the-c0d3r** [comment]
Hey, @santanor No problem. I am interested in C programming. And your project as well so I've kept an eye on it. I've looked at some code. They seem very interesting to me. Emulating the CPU, executing opcode, etc. I'm not that good yet in C so I cannot comprehend everything. But I'd very much like to contribute myself. If it's not too much trouble, can you like list a few issues with a small chunk of functionality and tag it something like "good first issue" or something? So that it's easy for newcomers like me to contribute, that is if you wish to have contributors?

As for my background, I have written some production level high-performance multithreaded C programs. And I also do a bit of basic reverse engineering and I have some cyber security background.

**Comment by alexsaezm** [comment]
You're comment makes me feel really proud of the project. Someone find it interesting! Really, I'm amazed.

Of course we'll make something for newcomers.

:D

**Comment by santanor** [comment]
+9001 to what @alexsaezm said. I'm in awe. 


>  I'm not that good yet in C so I cannot comprehend everything

We started this project to **learn** C. It's one of the main goals we had for this. We're open to **any** suggestion and given the background you provided it might be that you'll be teaching us as you've done **twice** already 👍 

We'll get some issues on the board with the right tags today and well documented so you can get cracking whenever you feel like it. Sounds good? 

See you on the Pull Request board :D

**Comment by santanor** [comment]
Closing this issue since the actual bug has been fixed. The discussion about zlog will continue on #36
